package dev.ktxvulkan.graphics.vk

object VkSurfacePresentModeKHR {
    const val VK_PRESENT_MODE_IMMEDIATE_KHR = 0
    const val VK_PRESENT_MODE_MAILBOX_KHR = 1
    const val VK_PRESENT_MODE_FIFO_KHR = 2
    const val VK_PRESENT_MODE_FIFO_RELAXED_KHR = 3
    const val VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR = 1000111000
    const val VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR = 1000111001
    const val VK_PRESENT_MODE_MAX_ENUM_KHR = 0x7FFFFFFF
}